// <auto-generated />
using System;
using GameCollector.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameCollector.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260815174619_AddUserProfilesAndDevices")]
    partial class AddUserProfilesAndDevices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("GameCollector.Domain.Users.DeviceRegistration", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_DeviceRegistrations_UserId");

                    b.ToTable("DeviceRegistrations", (string)null);
                });

            modelBuilder.Entity("GameCollector.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentitySubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdentitySubject")
                        .IsUnique()
                        .HasDatabaseName("UX_UserProfiles_IdentitySubject");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("UX_UserProfiles_NormalizedUsername");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("GameCollector.Domain.Users.DeviceRegistration", b =>
                {
                    b.HasOne("GameCollector.Domain.Users.UserProfile", "User")
                        .WithOne()
                        .HasForeignKey("GameCollector.Domain.Users.DeviceRegistration", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
