// <auto-generated />
using System;
using GameCollector.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameCollector.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260815175531_AddCollectionsAndInvitations")]
    partial class AddCollectionsAndInvitations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("GameCollector.Domain.Collections.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("GameCollector.Domain.Collections.CollectionInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InviteeUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InviterUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InviteeUserId");

                    b.HasIndex("InviterUserId");

                    b.HasIndex("CollectionId", "InviteeUserId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("CollectionInvitations", (string)null);
                });

            modelBuilder.Entity("GameCollector.Domain.Collections.CollectionMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CollectionId", "UserId")
                        .IsUnique();

                    b.ToTable("CollectionMembers", (string)null);
                });

            modelBuilder.Entity("GameCollector.Domain.Users.DeviceRegistration", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_DeviceRegistrations_UserId");

                    b.ToTable("DeviceRegistrations", (string)null);
                });

            modelBuilder.Entity("GameCollector.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultCollectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentitySubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultCollectionId");

                    b.HasIndex("IdentitySubject")
                        .IsUnique()
                        .HasDatabaseName("UX_UserProfiles_IdentitySubject");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("UX_UserProfiles_NormalizedUsername");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("GameCollector.Domain.Collections.Collection", b =>
                {
                    b.HasOne("GameCollector.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GameCollector.Domain.Collections.CollectionInvitation", b =>
                {
                    b.HasOne("GameCollector.Domain.Collections.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameCollector.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("InviteeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameCollector.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("InviterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("GameCollector.Domain.Collections.CollectionMember", b =>
                {
                    b.HasOne("GameCollector.Domain.Collections.Collection", "Collection")
                        .WithMany("Members")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameCollector.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("GameCollector.Domain.Users.DeviceRegistration", b =>
                {
                    b.HasOne("GameCollector.Domain.Users.UserProfile", "User")
                        .WithOne()
                        .HasForeignKey("GameCollector.Domain.Users.DeviceRegistration", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameCollector.Domain.Users.UserProfile", b =>
                {
                    b.HasOne("GameCollector.Domain.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("DefaultCollectionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GameCollector.Domain.Collections.Collection", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
