// <auto-generated />
using System;
using GameCollector.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameCollector.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260815182541_AddOwnershipAndWishlists")]
    partial class AddOwnershipAndWishlists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("GameCollector.Domain.Catalog.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("MaximumPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaximumPlayingTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinimumAge")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinimumPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinimumPlayingTimeMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModerationStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("SubmittedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModerationStatus");

                    b.HasIndex("SubmittedByUserId");

                    b.HasIndex("Title");

                    b.ToTable("Games", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "The classic matching game with a two-sided deck.",
                            MaximumPlayers = 10,
                            MaximumPlayingTimeMinutes = 30,
                            MinimumAge = 7,
                            MinimumPlayers = 2,
                            MinimumPlayingTimeMinutes = 15,
                            ModerationStatus = 2,
                            Publisher = "Mattel",
                            ReleaseYear = 2019,
                            Revision = 1L,
                            Title = "UNO Flip!",
                            UpdatedAtUtc = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("GameCollector.Domain.Catalog.GameBarcode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedBarcode")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("NormalizedBarcode")
                        .IsUnique();

                    b.ToTable("GameBarcodes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Barcode = "887961751062",
                            GameId = new Guid("30000000-0000-0000-0000-000000000001"),
                            NormalizedBarcode = "887961751062"
                        });
                });

            modelBuilder.Entity("GameCollector.Domain.Catalog.GameLanguage", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LanguageId")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("GameLanguages", (string)null);

                    b.HasData(
                        new
                        {
                            GameId = new Guid("30000000-0000-0000-0000-000000000001"),
                            LanguageId = new Guid("10000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("GameCollector.Domain.Catalog.GameTag", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("GameId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("GameTags", (string)null);

                    b.HasData(
                        new
                        {
                            GameId = new Guid("30000000-0000-0000-0000-000000000001"),
                            TagId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            GameId = new Guid("30000000-0000-0000-0000-000000000001"),
                            TagId = new Guid("20000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("GameCollector.Domain.Catalog.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "en",
                            Name = "English"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "nl",
                            Name = "Dutch"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "fr",
                            Name = "French"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "de",
                            Name = "German"
                        });
                });

            modelBuilder.Entity("GameCollector.Domain.Catalog.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Card Game"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Name = "Family"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Name = "Party"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Name = "Cooperative"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Name = "Fast"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            Name = "Two Player"
                        });
                });

            modelBuilder.Entity("GameCollector.Domain.Collections.Collection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("GameCollector.Domain.Collections.CollectionGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AddedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddedByUserId");

                    b.HasIndex("GameId");

                    b.HasIndex("CollectionId", "GameId")
                        .IsUnique();

                    b.ToTable("CollectionGames", (string)null);
                });

            modelBuilder.Entity("GameCollector.Domain.Collections.CollectionInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InviteeUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InviterUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InviteeUserId");

                    b.HasIndex("InviterUserId");

                    b.HasIndex("CollectionId", "InviteeUserId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 0");

                    b.ToTable("CollectionInvitations", (string)null);
                });

            modelBuilder.Entity("GameCollector.Domain.Collections.CollectionMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CollectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("CollectionId", "UserId")
                        .IsUnique();

                    b.ToTable("CollectionMembers", (string)null);
                });

            modelBuilder.Entity("GameCollector.Domain.Users.DeviceRegistration", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ActivatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_DeviceRegistrations_UserId");

                    b.ToTable("DeviceRegistrations", (string)null);
                });

            modelBuilder.Entity("GameCollector.Domain.Users.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DefaultCollectionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentitySubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NormalizedUsername")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultCollectionId");

                    b.HasIndex("IdentitySubject")
                        .IsUnique()
                        .HasDatabaseName("UX_UserProfiles_IdentitySubject");

                    b.HasIndex("NormalizedUsername")
                        .IsUnique()
                        .HasDatabaseName("UX_UserProfiles_NormalizedUsername");

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("GameCollector.Domain.Users.WishlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GameId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId", "GameId")
                        .IsUnique();

                    b.ToTable("WishlistItems", (string)null);
                });

            modelBuilder.Entity("GameCollector.Domain.Catalog.Game", b =>
                {
                    b.HasOne("GameCollector.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("SubmittedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("GameCollector.Domain.Catalog.GameBarcode", b =>
                {
                    b.HasOne("GameCollector.Domain.Catalog.Game", "Game")
                        .WithMany("Barcodes")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameCollector.Domain.Catalog.GameLanguage", b =>
                {
                    b.HasOne("GameCollector.Domain.Catalog.Game", "Game")
                        .WithMany("Languages")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameCollector.Domain.Catalog.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Language");
                });

            modelBuilder.Entity("GameCollector.Domain.Catalog.GameTag", b =>
                {
                    b.HasOne("GameCollector.Domain.Catalog.Game", "Game")
                        .WithMany("Tags")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameCollector.Domain.Catalog.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("GameCollector.Domain.Collections.Collection", b =>
                {
                    b.HasOne("GameCollector.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("GameCollector.Domain.Collections.CollectionGame", b =>
                {
                    b.HasOne("GameCollector.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("AddedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameCollector.Domain.Collections.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameCollector.Domain.Catalog.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameCollector.Domain.Collections.CollectionInvitation", b =>
                {
                    b.HasOne("GameCollector.Domain.Collections.Collection", "Collection")
                        .WithMany()
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameCollector.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("InviteeUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GameCollector.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("InviterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("GameCollector.Domain.Collections.CollectionMember", b =>
                {
                    b.HasOne("GameCollector.Domain.Collections.Collection", "Collection")
                        .WithMany("Members")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameCollector.Domain.Users.UserProfile", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("GameCollector.Domain.Users.DeviceRegistration", b =>
                {
                    b.HasOne("GameCollector.Domain.Users.UserProfile", "User")
                        .WithOne()
                        .HasForeignKey("GameCollector.Domain.Users.DeviceRegistration", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameCollector.Domain.Users.UserProfile", b =>
                {
                    b.HasOne("GameCollector.Domain.Collections.Collection", null)
                        .WithMany()
                        .HasForeignKey("DefaultCollectionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("GameCollector.Domain.Users.WishlistItem", b =>
                {
                    b.HasOne("GameCollector.Domain.Catalog.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameCollector.Domain.Users.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameCollector.Domain.Catalog.Game", b =>
                {
                    b.Navigation("Barcodes");

                    b.Navigation("Languages");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("GameCollector.Domain.Collections.Collection", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
